repos:
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    - id: cmake-format

  - repo: https://github.com/doublify/pre-commit-clang-format
    rev: master
    hooks:
    - id: clang-format
