image:
  - Visual Studio 2017

cache:
  - C:\Users\appveyor\.conan -> aide/dependencies/CMakeLists.txt

configuration:
  - Debug
  - Release

environment:
  matrix:
  - BUILD_SHARED_LIBS: 0
    QT5: C:\Qt\5.13.0\msvc2017_64

#  - BUILD_SHARED_LIBS: 1
#    QT5: C:\Qt\5.13.0\msvc2017_64

install:
- pip.exe install conan_package_tools
- pip.exe install --upgrade --user -r requirements.txt

before_build:
- set Path=%QT5%\bin;%Path%
- mkdir build
- cmake -DWARNINGS_AS_ERRORS=0 -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% -DCMAKE_PREFIX_PATH="%QT5%" -H. -Bbuild

build:
  verbosity: normal
  project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - cd build
  - ctest -V

on_success:
  - appveyor PushArtifact tests\ut\test_result.xml
  - sh: |
      echo "Test $APPVEYOR_JOB_ID"
      find "tests/ut" -type f -name 'test_result.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
