name: Publish Doxygen GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Install Doxygen
        run:
          sudo apt install doxygen graphviz -y

      - name: Build doxygen documentation
        run: |
          mkdir build
          cd build
          cmake .. -DENABLE_DOXYGEN=ON
          make doxygen-docs

      - name: Publish doxygen documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: build/aide/doc/html
          branch: gh_pages
          github_token: ${{ secrets.GITHUB_TOKEN }}