name: Build standalone and test installed lib

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        pip3 install wheel setuptools
        pip3 install --upgrade -r requirements.txt
        sudo apt install ^libxcb-*

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Build and install the library
      working-directory: aide
      run: |
        mkdir build_standalone
        cd build_standalone
        cmake -DCMAKE_INSTALL_PREFIX=~/.local/ -DUNIT_TESTS_RUN_ON_CI=1 ..
        cmake --build . --target install --config Release -j 4

    - name: Build the tests
      working-directory: tests
      run: |
        mkdir build_standalone
        cd build_standalone
        cmake -DCMAKE_INSTALL_PREFIX=~/.local/ -DUNIT_TESTS_RUN_ON_CI=1 ..
        cmake --build . --config Release -j 4

    - name: Test the project
      uses: GabrielBB/xvfb-action@v1
      with:
        working-directory: tests/build_standalone
        run: ctest

    - name: Upload Unit Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test_results_installed_lib
        path: tests/build_standalone/**/*.xml

  publish-test-results:
    name: "Publish Unit Test Results from installed lib"
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results installed lib
        uses: EnricoMi/publish-unit-test-result-action@v1.4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results install lib
          hide_comments: all but latest
          comment_on_pr: true
          files: artifacts/test_results_installed_lib/ut/*.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
